name: CMake (Ninja)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4.1.7
        with:
          submodules: recursive

      - name: Configure CMake (x64)
        run: cmake --preset ninja-x64

      - name: Build (x64)
        run: cmake --build --preset ninja-x64-release --verbose

      - name: Configure CMake (x86)
        run: cmake --preset ninja-x86

      - name: Build (x86)
        run: cmake --build --preset ninja-x86-release --verbose
